import {sanityClient} from "../../../lib/sanity";
import imageUrlBuilder from '@sanity/image-url';
import {PortableText} from '@portabletext/react';
import moment from 'moment';
import { motion } from "framer-motion";

import {useState, useEffect} from "react";
import Link from 'next/link';
import Head from "next/head";

import styles from '../../../styles/Post.module.css';

import { MdArrowLeft, MdArrowRight } from "react-icons/md"; 
import Footer from '../../../components/Footer/Footer';


const builder = imageUrlBuilder(sanityClient);
function urlFor(source){
  return builder.image(source)
}

const postQuery = `*[_type == "post" && slug.current == $slug][0]{
    title,
    slug,
    location,
    overview,
    author,
    categories[]->{title},
    mainImage,
    publishedAt,
    body,
}`

const contactQuery =`*[_type in ["landpage"]]| order(publishedAt desc){
    email,
    phoneNumber
}`




export default function Post({ data }) {


    

    const {post, nextPost, previousPost, contacts } = data; 
    const [isOn, setIsOn] = useState(false);
    const [colorTheme, setColorTheme] = useState(["bkgBeige", "blackFont"]);


    function Switch({ isOn, ...props }) {
        const className = `switch ${isOn ? "on" : "off"}`;

        return (
          <motion.div animate className={className} {...props}>
            <motion.div animate />
          </motion.div>
        );
      }

      function handleSwitch(){
        setIsOn(!isOn);

        switch (isOn) {
            case false:
                setColorTheme(["bkgBlack", "beigeFont"])        
                break;

            case true:
                setColorTheme(["bkgBeige", "blackFont"])
                break;
        
            default:
                setColorTheme(["bkgBeige", "blackFont"])
                break;
        }
      }

    


return(

<div className={`${colorTheme[0]} ${colorTheme[1]} ${styles.container}`}>
    <Head>
        <title>{post?.title}</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
    </Head>

<main className={styles.main}>
    
    <div className={styles.title}>
        <h2 className="noto-serif size-70">{post?.title}</h2>
    </div>

    <div className={`orangeDarkfont size-21 dm-sams ${styles.date}`}>
        <div>
            <p>{moment(post?.publishedAt, "YYYY-MM-DD").format("MMMM Do YYYY")}</p>
            <p>{post?.location}</p>
        </div>

        <div>
            <Switch isOn={isOn} onClick={handleSwitch}/>
        </div>
    </div>

    <section className={styles.overview}>
        <p className={`size-21`}>{post?.overview}</p>
    </section>


    <article className={`size-21 ${styles.post}`}>

        <div className={styles.imageContainer}>
            <img src={urlFor(post?.mainImage)
                .width(710)
                .height(400)
                .url()} 
                alt={post?.title}
                className={styles.image}
                >
            </img>
        </div>


        <PortableText value={post.body}/>

        <div className={styles.tagsContainer}>
                {post.categories?.length > 0 && post.categories.map((item) => (
                <span key={item.title} className={`orangeDarkfont size-21 ${styles.tag}`}>#{item.title}</span>
                ))}
        </div>


    </article>

    <div className={`size-28 ${styles.morePosts}`}>
        <Link href={`/blog/posts/${previousPost.slug.current}`}>
        <a>
            <MdArrowLeft size='120px' className={styles.arrowIcon}/>
        </a>
        </Link>
            
        <p>More Posts</p>

        <Link href={`/blog/posts/${nextPost.slug.current}`}>
        <a>
            <MdArrowRight size='120px' className={styles.arrowIcon}/>
        </a>
        </Link>
    </div>
    
</main>

<section>
<Footer bkgColor={colorTheme[0]} contactColor="orangeDarkfont" email={contacts[0].email} phoneNumber={contacts[0].phoneNumber}/>
</section>

</div>
)
}

export async function getStaticPaths() {
 
    const paths = await sanityClient.fetch(
        `*[_type == "post" && defined(slug.current)]{

            "params": {
                "slug": slug.current
            }
        }`

    )

    return {
        paths,
        fallback: true
    }
    
}

export async function getStaticProps({ params }) {
    const { slug } = params;
    const currentPost = await sanityClient.fetch(postQuery, { slug });
    const contacts = await sanityClient.fetch(contactQuery);


    const posts = await sanityClient.fetch(`*[_type in ["post"]]| order(publishedAt desc){
        title,
        slug,
        location,
        overview,
        author,
        categories[]->{title},
        mainImage,
        publishedAt,
        body,
          }`);
          
          const currentPostIndex = posts.findIndex(item => item.slug.current === currentPost.slug.current);
          const lastIndex = posts.length -1;
          let previousPostIndex = 0;
          let nextPostIndex = 0;
  
        
            if(currentPostIndex == 0){
                previousPostIndex = 0;
            } else {
                previousPostIndex = currentPostIndex - 1;
            }

            if(currentPostIndex == lastIndex ){
                nextPostIndex = currentPostIndex;
            } else {
                nextPostIndex = currentPostIndex + 1;
            }

          const nextPost = posts[nextPostIndex];
          const previousPost = posts[previousPostIndex];
          const post = posts[currentPostIndex];
          
          

    return { props: { data: { post, nextPost, previousPost, contacts } } };
    
}

