import Head from 'next/head';
import Image from 'next/image';
import NavBar from '../components/NavBar/NavBar';
import styles from '../styles/Home.module.css'

import CardsWorks from '../components/CardsWorks/CardsWorks';
import BigBot from '../components/BigBot/BigBot';
import SmallBot from '../components/SmallBot/SmallBot';
import BlogSec from '../components/BlogSec/BlogSec';
import Footer from '../components/Footer/Footer';



export default function Home() {
  return (
  <div className={styles.indexClass}>
    <Head>
        <title>Rodrigo Francalacci Song Blog</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
    </Head>
    <NavBar/>

{/* section 1 - home cover */}
    <section className={`${styles.homeCover}`}>
      <div className={styles.margin_B_240_275}><BigBot/></div>
      </section>

{/* section 2 - album */}
    <section className={`${styles.album}`}>

      <div className={`size-49a ${styles.albumTitle}`}>
        <div className={`${styles.height_97_143}`}></div>
        <h2>Sunny Days</h2>
      </div>

      <SmallBot text={"Listen"} colorClass={"orangeDarkBot"}/>

      <div className={styles.width_986_432}>
        <div className={`${styles.albumImgContainer}`}>
        <img src="/img/home-viny.png" alt="image content" className={`${styles.albumImage}`}></img>
        </div>
      </div>

      <div className={styles.width_986_432}>
        <div className={`${styles.albumDescription} ${styles.margin_BT_102_78}`}>
            <p className={`size-28p`}>The "Sunny Day" is the first album solo of Rodrigo Francalacci.</p>
            <p className={`size-28p`}>It's was realeased in 2022 and recorded in the Abbey Road Studio.</p>
        </div>
      </div>

      <div className={`${styles.bar} ${styles.width_842_360}`}></div>


    </section>

{/* section 3 - works */}
    <section className={`${styles.works}`}>

      <div className={`${styles.margin_T_51_93}`}>
      <h2 className={`size-28`}>Works</h2>
      </div>
      

      <div className={`${styles.worksCardsContainer} ${styles.margin_B_42_102}`}>
        <CardsWorks/>
        <CardsWorks/>
        <CardsWorks/>
      </div>

    </section>

{/* section 4 - about */}
    <section className={`${styles.about}`}>


        <div className={`${styles.aboutContent} ${styles.margin_T_253_170}`}>

          <div className={styles.margin_L_933_150}>
              <div className={`${styles.width_581_237}`}>
                  <h2 className={`size-49a`}>Rodrigo Francalacci</h2>
                  <p className={`size-21`}>Rodrigo Francalacci (born 1987) is an Brazilian singer-songwriter, based in the United Kingdom. Francalacci's music combines rock and folk, his lyrics tell about love, faith and nostalgic feelings.</p>
                  <p className={`size-21`}>On March, 2022, Francalacci released the first album, titled "Sunsrise" and recorded in the Abbey Road Studio.</p>
              </div>
          </div>

        </div>


    </section>

{/* section 5 - blog */}
    <section className={`${styles.blog}`}>
     <div><BlogSec/></div>
    </section>

{/* section 6 - contact */}
    <section className={`${styles.contact}`}>

        <div className={`${styles.contactContent}`}>

          <h2 className={`size-70`}>Social Media</h2>

          <ul className={`size-49 ${styles.contacList}`}>
            <li>Spotify</li>
            <li>Youtube</li>
            <li>Facebook</li>
            <li>Instagran</li>
          </ul>

        </div>

    </section>

{/* footer- album */}
    <section className={`${styles.footer}`}>
      <Footer bkgColor="bkgOrangeDark"/>
    </section>


    
    


   </div>
  )
}
