import {sanityClient} from "../lib/sanity";
import imageUrlBuilder from '@sanity/image-url';
import {PortableText} from '@portabletext/react';
import {useState, useEffect} from "react";
import styles from '../styles/Home.module.css';

import Head from 'next/head';
import NavBar from '../components/NavBar/NavBar';
import CardsWorks from '../components/CardsWorks/CardsWorks';
import BigBot from '../components/BigBot/BigBot';
import SmallBot from '../components/SmallBot/SmallBot';
import BlogSec from '../components/BlogSec/BlogSec';
import Footer from '../components/Footer/Footer';
import { IoLogoDesignernews } from "react-icons/io5";

const builder = imageUrlBuilder(sanityClient);
function urlFor(source){
  return builder.image(source)
}

const sanityQuery = `{
  "albumInfo": *[_type in ["home"]]{
  newAlbumLink,
  newAlbumCover,
  newAlbumDescription,
  blogDescription,
  },

  "mediaInfo": *[_type in ["socialMedia"]]{
    mediaName,
    link,
  },

"worksInfo": *[_type in ["works"]]{
    albumName,
    albumYear,
    albumLink,
    AlbumCover,
  
  }
}`;


export default function Home({ data }) {

  const mediaInfo = data.mediaInfo;
  const albumInfo = data.albumInfo[0];
  const works = data.worksInfo;

  return (
  <div className={styles.indexClass}>
    <Head>
        <title>Rodrigo Francalacci Song Blog</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
    </Head>
    <NavBar/>

{/* section 1 - home cover */}
    <section className={`${styles.homeCover}`}>
      <div className={styles.margin_B_240_275}><BigBot/></div>
      </section>

{/* section 2 - album */}
    <section className={`${styles.album}`}>

      <div className={`size-49a ${styles.albumTitle}`}>
        <div className={`${styles.height_97_143}`}></div>
        <h2>Sunny Days</h2>
      </div>

      <SmallBot text={"Listen"} colorClass={"orangeDarkBot"}/>

      <div className={styles.width_986_432}>
        <div className={`${styles.albumImgContainer}`}>
        
        <img src={urlFor(albumInfo.newAlbumCover).url()} alt="image content" className={`${styles.albumImage}`}></img>
        </div>
      </div>

      <div className={styles.width_986_432}>
        <div className={`${styles.albumDescription} ${styles.margin_BT_102_78}`}>
        
        <div className={`size-28p`}>
          <PortableText value={albumInfo.newAlbumDescription}/>
        </div>
          
    
        </div>
      </div>

      <div className={`${styles.bar} ${styles.width_842_360}`}></div>


    </section>

{/* section 3 - works */}
    <section className={`${styles.works}`}>

      <div className={`${styles.margin_T_51_93}`}>
      <h2 className={`size-28`}>Works</h2>
      </div>
      

      <div className={`${styles.worksCardsContainer} ${styles.margin_B_42_102}`}>

      {works?.length > 0 && works.map((item) => (

<CardsWorks name={item.albumName} year={item.albumYear} link={item.albumLink} img={item.AlbumCover}/>

))}

       
        
      </div>

    </section>

{/* section 4 - about */}
    <section className={`${styles.about}`}>


        <div className={`${styles.aboutContent} ${styles.margin_T_253_170}`}>

          <div className={styles.margin_L_933_150}>
              <div className={`${styles.width_581_237}`}>
                  <h2 className={`size-49a`}>Rodrigo Francalacci</h2>
                  <p className={`size-21`}>Rodrigo Francalacci (born 1987) is an Brazilian singer-songwriter, based in the United Kingdom. Francalacci's music combines rock and folk, his lyrics tell about love, faith and nostalgic feelings.</p>
                  <p className={`size-21`}>On March, 2022, Francalacci released the first album, titled "Sunsrise" and recorded in the Abbey Road Studio.</p>
              </div>
          </div>

        </div>


    </section>

{/* section 5 - blog */}
    <section className={`${styles.blog}`}>
     <div><BlogSec blogDescription={albumInfo.blogDescription}/></div>
    </section>

{/* section 6 - contact */}
    <section className={`${styles.contact}`}>

        <div className={`${styles.contactContent}`}>

          <h2 className={`size-70`}>Social Media</h2>

          <ul className={`size-49 ${styles.contacList}`}>

            {mediaInfo?.length > 0 && mediaInfo.map((item) => (

              <li key={item.mediaName}><a href={item.link}>{item.mediaName}</a></li>

            ))}
            
          </ul>

        </div>

    </section>

{/* footer- album */}
    <section className={`${styles.footer}`}>
      <Footer bkgColor="bkgOrangeDark"/>
    </section>


   </div>
  )
}

export async function getStaticProps(){

  const data = await sanityClient.fetch(sanityQuery);

  return {props: {data}};
}

// yarn upgrade @sanity/cli 